services:
  app:
    build: .
    container_name: api-productos
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    environment:
      - GIN_MODE=release

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mydatabase
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: